---
# tasks file for openvpn-easyrsa
- name: Install easy rsa
  apt:
    name: easy-rsa=3.0.6-1
  when: inventory_hostname == easy_rsa_host

- name: Init PKI
  shell: echo 'yes' | easyrsa init-pki
  args:
    chdir: /root
    creates: "{{PKI_DIR}}"
  environment:
    PATH: "{{ EASY_RSA_BIN }}:{{ansible_env.PATH}}"
  when: inventory_hostname == easy_rsa_host

- name: Build CA
  expect:
    command: easyrsa build-ca nopass
    chdir: /root
    creates: "{{PKI_DIR}}/{{ca_cn}}.crt"
    responses:
      'Common Name \(eg: your user, host, or server name\) \[Easy-RSA CA\]:$': "{{ca_cn}}"
  environment:
    PATH: "{{ EASY_RSA_BIN }}:{{ansible_env.PATH}}"
  when: inventory_hostname == easy_rsa_host