---
# tasks file for openvpn-client
- include_role:
    name: openvpn-generic

- name: Copy ta key to the client
  shell: rsync -az --rsh="/usr/bin/sshpass -p {{ansible_password}} ssh -o StrictHostKeyChecking=no -l root" "{{hostvars[server_host]['ansible_default_ipv4']['address']}}:{{host_pki_dir}}/ta.key" "{{host_pki_dir}}/ta.key"
  args:
    creates: "{{host_pki_dir}}/ta.key"

- name: Build Client Cert
  shell: easyrsa --subject-alt-name="{{id_type}}:{{ansible_host}}" build-client-full {{ansible_host}} nopass
  args:
    chdir: /root
    creates: "{{PKI_DIR}}/issued/{{ansible_host}}.crt"
  environment:
    PATH: "{{ EASY_RSA_BIN }}:{{ansible_env.PATH}}"
  delegate_to: "{{easy_rsa_host}}"

- name: Copy client cert to the client
  shell: rsync -az --rsh="/usr/bin/sshpass -p {{ansible_password}} ssh -o StrictHostKeyChecking=no -l root" "{{hostvars[easy_rsa_host]['ansible_default_ipv4']['address']}}:{{PKI_DIR}}/issued/{{ansible_host}}.crt" "{{host_pki_dir}}/{{ansible_host}}.crt"
  args:
    creates: "{{host_pki_dir}}/{{ansible_host}}.crt"
  

- name: Copy client key to the client
  shell: rsync -az --rsh="/usr/bin/sshpass -p {{ansible_password}} ssh -o StrictHostKeyChecking=no -l root" "{{hostvars[easy_rsa_host]['ansible_default_ipv4']['address']}}:{{PKI_DIR}}/private/{{ansible_host}}.key" "{{host_pki_dir}}/{{ansible_host}}.key"
  args:
    creates: "{{host_pki_dir}}/{{ansible_host}}.key"

- name: Copy CA to the client
  shell: rsync -az --rsh="/usr/bin/sshpass -p {{ansible_password}} ssh -o StrictHostKeyChecking=no -l root" "{{hostvars[easy_rsa_host]['ansible_default_ipv4']['address']}}:{{PKI_DIR}}/{{ca_cn}}.crt" "{{host_pki_dir}}/{{ca_cn}}.crt"
  args:
    creates: "{{host_pki_dir}}/{{ca_cn}}.crt"

- name: Template client.conf
  template:
    src: templates/client.conf
    dest: /etc/openvpn/client.conf
    mode: '0660'

- name: Template ccd
  template:
    src: templates/ccd.conf
    dest: /etc/openvpn/ccd/{{ansible_host}}
    mode: '0660'
  delegate_to: server

- name: Restart client
  shell: systemctl restart openvpn@client.service

- name: Enable client
  shell: systemctl enable openvpn@client.service
  